sonar.projectKey=NBUSW_NVMesh_NVMesh_nvmesh-management
sonar.qualitygate.wait=true
sonar.host.url=https://sonar.nvidia.com/

sonar.sources=.
sonar.coverage.exclusions=**/*README*
sonar.exclusions=test/**,slash-tests/**,**/examples/**,**/*.min.js,**/*.map,simulation/**
sonar.test.inclusions=test/**,slash-tests/**
