#!/bin/bash

management_transfer_list="scripts/add_cluster_identification.js \
				scripts/nonInteractiveStartup.js \
				scripts/deleteAllKafkaTopics.js \
				allocationSanity.js \
				app.js \
				bin \
				bootstrapper.js \
				childProcess.js \
				clearDB.js \
				consts.js \
				dbBackup.js \
				events.js \
				initDB.js \
				initServices \
				logger.js \
				management.js.conf \
				models \
				modules \
				node_modules \
				objectNotifier.js \
				package.json \
				.babelrc.js \
				public \
				queue.js \
				routes \
				middlewares \
				services \
				system.d \
				systemMessages.js \
				upgradeScripts \
				utils.js \
				validationSchemes \
				views \
				dl \
				interop-db"

utils_transfer_list="scripts/nvmesh_diag \
			scripts/nvmesh_logs_collector \
			RPM/docker/kubernetes/examples/"

nhc_transfer_list="nhc/nhc_files"

utils_optional_transfer_list="infrastructure/dist"
