#!/bin/bash -x

source ../transfer_lists

print_help() {
    cat <<EOF
usage:

-h      --help              prints this help

-b      --branch            branch name

-c      --commit-id         commit id

-g      --change-id         change id

-d      --git-describe      git describe string

-s	--skin		    choose skin

-S	--sign-rpm	    sign the rpm

-u      --utils               build utils rpm

-M      --management        build management rpm

-n      --nhc               build nhc rpm

--build-docker-image        build Docker image

--dist-tag		    distribution tag to include in the RPM name

--ubuntu		    create deb package for ubuntu

--skip-dependency-generation  skip internal dependency generation (fast build - only for dev purposes)

--skip-stripping              skip stripping and post-install scripts (fast build - only for dev purposes)
EOF
}

validate_buildrpm_dependencies_installed() {
    # Check if environment variable is set
    if [ -z "$BUILDRPM_DEPENDENCIES" ]; then
        echo "Error: BUILDRPM_DEPENDENCIES environment variable is not set or empty"
        return 1
    fi

    local missing_packages=()

    # Determine the package check command based on OS
    if [ -e /etc/redhat-release ]; then
        check_cmd="rpm -q"
    elif [[ "$(cat /etc/os-release 2>/dev/null)" =~ Ubuntu ]]; then
        check_cmd="dpkg -l"
    else
        echo "Error: Unable to determine OS type (neither RedHat nor Ubuntu detected)"
        return 1
    fi

    # Check each package
    for package in $BUILDRPM_DEPENDENCIES; do
        if ! $check_cmd "$package" >/dev/null 2>&1; then
            missing_packages+=("$package")
        fi
    done

    # If there are missing packages, report them and exit with error
    if [ ${#missing_packages[@]} -gt 0 ]; then
        echo "Error: The following packages are not installed:"
        printf '%s\n' "${missing_packages[@]}"
        return 1
    fi

    return 0
}

buildRPMSetupTree() {
    if test -e /etc/redhat-release; then
        echo "Building RPM on Redhat-based distro. Running rpmdev-setuptree"
        rpmdev-setuptree
    else
        echo "Building RPM on non Redhat-based distro. Assuming Ubuntu. Manually setting up $rpm_build_dir"
        mkdir -p $rpm_build_dir/{SPECS,BUILD,BUILDROOT,SOURCES,RPMS/$ARCH,SRPMS}
    fi
}

skipDependencyGeneration=false
skipStripping=false

pkgDeb() {
    if $isUbuntu || [[ "$DISTRIBUTION_INFO" =~ "Ubuntu" ]]; then
        echo "Building Ubuntu deb package..."
        ubuntu_dir="ubuntu_deb_build"
        mkdir $ubuntu_dir
        cd $ubuntu_dir

        if [ $ARCH == aarch64 ]; then
            ATARGET=--target=arm64
        else
            ATARGET=
        fi

        start_alien=$(date +%s)
        alien --generate -k --scripts ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"* $ATARGET
        end_alien=$(date +%s)
        echo "Alien generation took $((end_alien - start_alien)) seconds."

        packDir=$packagePrefix-$rpm_version

        if [ -e $packDir/debian ]; then
            if [ $rpm == $mgmt ] || [ $rpm == $utils ]; then
                echo "Configuring deb dependencies..."
                sed -i -E "s/^[ ]*Depends:\s.*$/&, $requiresUbuntu/g" $packDir/debian/control
            fi

            if [ "$skipStripping" == "true" ] && [ $rpm == $mgmt ]; then
                echo "Excluding node_modules from dh_strip_nondeterminism..."
                printf "\noverride_dh_strip_nondeterminism:\n\tdh_strip_nondeterminism -Xnode_modules\n" >> $packDir/debian/rules
            fi

            echo "Setting gzip compression..."
            sed -i -E "s/dh_builddeb$/dh_builddeb -- -Zgzip/g" $packDir/debian/rules

            cd $packDir

            start_dpkg=$(date +%s)
            dpkg-buildpackage -uc -us
            end_dpkg=$(date +%s)
            echo "dpkg-buildpackage took $((end_dpkg - start_dpkg)) seconds."

            cd ..
            rm -rf $packDir
            cp *.deb ../
        fi

        cd ..
        rm -rf $ubuntu_dir
    fi
}

mgmtRPM=true
utilsRPM=false
nhcRPM=false
isUbuntu=false
ignoreWarning=false
buildNum="buildnumber" #default place holder for non-official build


while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -h|--help)
    print_help
    exit 0
    ;;
    -b|--branch)
    branchName="$2"
    shift
    ;;
    -c|--commit-id)
    commitID="$2"
    shift
    ;;
    -g|--change-id)
    changeID="$2"
    shift
    ;;
    -d|--git-describe)
    describe="$2"
    shift
    ;;
    -s|--skin)
    skin="$2"
    shift
    ;;
    -S|--sign-rpm)
    signRPM=true
    ;;
    -u|--utils)
    utilsRPM=true
    mgmtRPM=false
    ;;
    -M|--management)
    mgmtRPM=true
    ;;
    -n|--nhc)
    nhcRPM=true
    mgmtRPM=false
    ;;
    --build-docker-image)
        buildDockerImage=true
        ;;
    --dist-tag)
        distTag="$2"
        shift
        ;;
    --ubuntu)
        isUbuntu=true
        ;;
    --build-number)
	buildNum="$2"
	shift
	;;
    --skip-dependency-generation)
        skipDependencyGeneration=true
        ;;
    --skip-stripping)
        skipStripping=true
        ;;
    *)
        # unknown option
        echo "Unknown option $key"
        print_help
        exit 1
        ;;
    esac
    shift # past argument or value
done

if [ "$mgmtRPM" == true ]; then
    . ./buildrpm_dependencies.env
    if ! validate_buildrpm_dependencies_installed; then
        echo "Package validation failed"
        exit 1
    fi
fi

rpmsToCreate=()
utils="utils"
mgmt="management"
nhc="nhc"

if [ -z "$DISTRIBUTION_INFO" ]; then
    DISTRIBUTION_INFO=$(cat /etc/*release)
fi

if [ "$utilsRPM" == true ]; then
    rpmsToCreate+=($utils)
fi

if [ "$mgmtRPM" == true ]; then
    rpmsToCreate+=($mgmt)
fi

if [ "$nhcRPM" == true ]; then
    rpmsToCreate+=($nhc)
fi

if [ -z $commitID ]; then
    commitID=$(git log -n1 --format=%h)
fi

if [ -z $changeID ]; then
    changeID=$(git log -n1 --format=%b | awk '/^Change-Id: / {print $2}')
fi

if [ -z $branchName ]; then
    branchName=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
fi

if [ -z $distTag ]; then
    if [ -e /etc/redhat-release ]; then
        redhat_rel_content=$(cat /etc/redhat-release)
        if [[ "$redhat_rel_content" =~ ([0-9]+).([0-9]+) ]]; then
            minor_ver=${BASH_REMATCH[2]}
            rpm_dist_tag=$(rpm --eval='%{?dist}')
            if [ -z "$minor_ver" ] || [ -z "$rpm_dist_tag" ]; then
                echo "ERROR: cannot find the distribution version"
                exit 1
            fi

            # check where to place the minor version
            IFS='.' read -r -a rpm_dist_tag_arr <<<"$rpm_dist_tag"

            if [ ${#rpm_dist_tag_arr[@]} -eq 3 ]; then
                distTag=".${rpm_dist_tag_arr[1]}"_"$minor_ver"
            else
                distTag="$rpm_dist_tag"_"$minor_ver"
            fi
        fi
    else
        #not rhel related os - ubuntu or other
        os_version_id=$(grep -oP '^VERSION_ID="*\K[^"]*' /etc/os-release)
        if [ -n "$os_version_id" ]; then
            short_version_id=$(echo $os_version_id | tr -d .)
            os_name=$(grep -oP '^NAME="*\K[^."]*' /etc/os-release)
            if [ -n "$os_name" ]; then
                # convert to lower case
                lower_os_name=$(echo "$os_name" | awk '{print tolower($0)}')
                # remove spaces
                lower_os_name=${lower_os_name//[[:blank:]]/}
                distTag=".$lower_os_name$short_version_id"
            fi
        fi
    fi

    if [ -z "$distTag" ]; then
        echo "ERROR: could not find the distribution name and version to append to the RPM name"
    fi
fi

if [ -z $describe ]; then
    describe=$(git describe | cut -c 2-)
elif [[ $describe == v* ]]; then
    describe=$(echo $describe | cut -c 2-)
fi

IFS='-' read -ra gitDescribe <<<"$describe"

rpm_version="${gitDescribe[0]}"
rpm_release_num="${gitDescribe[1]}"
rpm_release="${rpm_release_num}$distTag.$buildNum"

echo "VERSION: $rpm_version RELEASE: $rpm_release"

rpm_build_dir=$(readlink -f ~/rpmbuild)
ARCH=$(uname -m)
echo "${rpmsToCreate[@]}"
for rpm in "${rpmsToCreate[@]}"; do
    buildRPMSetupTree

    cp rpmmacros $HOME/.rpmmacros

    packagePrefix="nvmesh-${rpm}"
    cp nvmesh-$rpm.spec ~/rpmbuild/SPECS/
    rm ~/rpmbuild/RPMS/$ARCH/$packagePrefix*$ARCH.rpm

    if [ $rpm == $utils ]; then
        cd ..
	commonRequirements="coreutils, grep"
        requires="$commonRequirements, rpm"
	requiresUbuntu="$commonRequirements, dpkg"
        rsync -aRPq --exclude=*.pyc $utils_transfer_list ~/"rpmbuild/SOURCES/$packagePrefix"
        rsync --ignore-missing-args -aRPq --exclude=*.pyc $utils_optional_transfer_list ~/"rpmbuild/SOURCES/$packagePrefix"
        cd RPM
    elif [ $rpm == $mgmt ]; then
        cd ..
        requires="systemd, nodejs >= 1:17.0.0-0, nodejs < 2:19.0.0-0, mongodb-mongosh >= 2.1, mongodb-mongosh < 2.6, mongodb-org-tools >= 5.0, mongodb-org-tools < 8.3, nvmesh-utils >= 2.0.0"
        requiresUbuntu="systemd, nodejs (>= 17.0.0), nodejs (<< 19.0.0), mongodb-mongosh (>= 2.1), mongodb-mongosh (<< 2.6), mongodb-org-tools (>= 5.0), mongodb-org-tools (<< 8.3), nvmesh-utils (>= 2.0.0)"

        rsync -av --exclude='.git/' ../interop-db/ ./interop-db
        rsync -aRPq --exclude=*~ $management_transfer_list ~/"rpmbuild/SOURCES/$packagePrefix"
        rm -rf ./interop-db/

        #making sure all the upgrade scripts have executable permissions before packaging them
        echo "Chmoding upgrade scripts..."
        chmod +x ~/rpmbuild/SOURCES/$packagePrefix/upgradeScripts/*

        find ~/"rpmbuild/SOURCES/$packagePrefix/upgradeScripts/" -maxdepth 1 ! -name '[0-9a-zA-Z]*' -type f -exec rm -f {} +

        #handling other vendors resources (public dir)
        if [ "$skin" == "micron" ]; then
            cp -Rp ~/"rpmbuild/SOURCES/$packagePrefix/public_micron"/* ~/"rpmbuild/SOURCES/$packagePrefix/public/"
        fi

        #deleting other skins
        rm -rf ~/"rpmbuild/SOURCES/$packagePrefix/public_micron"

        mkdir ~/"rpmbuild/SOURCES/$packagePrefix/installation"
        cd RPM
        cp *install* ~/"rpmbuild/SOURCES/$packagePrefix/installation"
    elif [ $rpm == $nhc ]; then
        tmp_nhc_dir='../nhc/nhc_files'
        mkdir $tmp_nhc_dir
        nhc_files=$(ls ../nhc | grep -E "nvmesh_.*.sh\b" | grep -v nvmesh_nhc_cache.sh | grep -v nvmesh_diag)
        cp ../nhc/nvmesh_nhc_cache.sh $tmp_nhc_dir

        for nhc_file in $nhc_files; do
            nhc_file=${nhc_file/.sh/}
            cp ../nhc/${nhc_file}.sh ${tmp_nhc_dir}/${nhc_file}.nhc
        done

        cd ..
        rsync -aRPq $nhc_transfer_list ~/"rpmbuild/SOURCES/$packagePrefix"
        cd RPM
        rm -rf ${tmp_nhc_dir}
    fi

    rm -fr ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"*

    if [ "$skipDependencyGeneration" == "true" ] && [ $rpm == $mgmt ]; then
        echo "Skipping dependency generation enabled."
        skipDepGenInt=1
    else
        skipDepGenInt=0
    fi

    if [ "$skipStripping" == "true" ] && [ $rpm == $mgmt ]; then
        echo "Skipping stripping enabled."
        skipStripInt=1
    else
        skipStripInt=0
    fi

    echo "Starting rpmbuild for $rpm..."
    start_rpmbuild=$(date +%s)

    if [ $rpm == $utils ]; then
	    rpmbuild -ba ~/rpmbuild/SPECS/nvmesh-$rpm.spec --define "commit_id $commitID" --define "change_id $changeID" --define "branch $branchName" --define "version $rpm_version" --define "release $rpm_release" --define "requires $requires"
        rpm_creation_retval=$?
        utilsPackageFile=$(find ~/rpmbuild/RPMS/$ARCH/$packagePrefix*)
    elif [ $rpm == $mgmt ]; then
        rpmbuild -ba ~/rpmbuild/SPECS/nvmesh-$rpm.spec --define "commit_id $commitID" --define "change_id $changeID" --define "branch $branchName" --define "version $rpm_version" --define "release $rpm_release" --define "requires $requires" --define "skip_dependency_generation $skipDepGenInt" --define "skip_stripping $skipStripInt"
        rpm_creation_retval=$?
        mgmtPackageFile=$(find ~/rpmbuild/RPMS/$ARCH/$packagePrefix*)
    elif [ $rpm == $nhc ]; then
        rpmbuild -ba ~/rpmbuild/SPECS/nvmesh-$rpm.spec --define "commit_id $commitID" --define "change_id $changeID" --define "branch $branchName" --define "version $rpm_version" --define "release $rpm_release"
        rpm_creation_retval=$?
        nhcPackageFile=$(find ~/rpmbuild/RPMS/$ARCH/$packagePrefix*)
    fi

    end_rpmbuild=$(date +%s)
    echo "rpmbuild for $rpm took $((end_rpmbuild - start_rpmbuild)) seconds."

    cp ~/"rpmbuild/RPMS/$ARCH/$packagePrefix"* .

    rm -rf ~/rpmbuild/SPECS/nvmesh-$rpm.spec ~/"rpmbuild/SOURCES/$packagePrefix" ~/"rpmbuild/BUILD/"* ~/"rpmbuild/BUILDROOT/"*

    if [ "$rpm_creation_retval" -eq "0" ] && [ "$signRPM" == true ]; then
        new_rpm="$packagePrefix*$rpm_version-$rpm_release*.rpm"
        echo "Signing RPM..."
        rpm --addsign $new_rpm
        if [ "$?" -ne "0" ]; then
            echo "Failed to sign RPM!"
        fi
    fi

    pkgDeb
done

build_docker_image() {
    echo "Building Docker Image from package $mgmtPackageFile with utils $utilsPackageFile"

    cp $mgmtPackageFile docker/src/
    cp $utilsPackageFile docker/src/

    cd docker/src

    utilsPkgFileWithoutPath=$(echo $utilsPackageFile | rev | cut -d '/' -f 1 | rev)
    mgmtPkgFileWithoutPath=$(echo $mgmtPackageFile | rev | cut -d '/' -f 1 | rev)

    ./build.sh --mgmt $mgmtPkgFileWithoutPath --utils $utilsPkgFileWithoutPath

    return_code=$?

    if [ "$return_code" -eq 0 ]; then
        rm ./$mgmtPkgFileWithoutPath
        cd ../../

        export_docker_image
        return $?
    else
        echo "Error building docker image"
        return $return_code
    fi
}

export_docker_image() {
    full_tag="$rpm_version-$rpm_release_num"
    tar_file_name="nvmesh-management-$full_tag.tar"
    image_name="registry.excelero.com/nvmesh-management:$full_tag"

    echo "Saving docker image $image_name to file $tar_file_name"

    docker save --output "$tar_file_name" "$image_name"
    return_code=$?

    if [ "$return_code" -ne 0 ]; then
        echo "Error saving docker image $image_name to file $tar_file_name"
    fi

    return $return_code
}

if [ "$buildDockerImage" == true ]; then
    build_docker_image
fi
