# Default values for nvmesh-management
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: nvmesh-management

config:
  useSSL: false
  loggingLevel: DEBUG
  mongoConnection:
    hosts: mongo.nvmesh.svc.cluster.local:27017
  statisticsMongoConnection:
    hosts:  mongo.nvmesh.svc.cluster.local:27017
  statisticsCores: 5
  statisticsIngressPort: 443

replicas: 1
image:
  repository: registry.acme.com/nvmesh-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  wsPort: 4001
  externalIP: null

guiService:
  type: ClusterIP
  port: 4000
  nodePort: null
  externalIP: null
  sessionAffinity: ClientIP

# ingressType, the type of ingress controller deployed in the setup, this will add some required configuration to the ingress object that are spcific to this ingress controllers
# allow values:
# null - No ingress will be deployeds
# ingress-nginx - Kubernetes NGINX based Ingress Controller (https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/) - Not to confused with NGINX own kubernetes ingress controller (nginx-ingress)
# traefik - Traefik Kuberenets Ingress Controller (https://docs.traefik.io/providers/kubernetes-ingress/)
ingressType: ingress-nginx

backupsVolume:
  deploy: true
  sharedStorage: false
  storageSize: 10Gi

# configuration for deploying mongo
mongo:
  deploy: false
  version: 4.2
  replicas: 3
  storageSize: 10Gi
  replicaSetName: rs0

# overrideKubeVersion - this is to workaround the missing flag --kube-version (https://github.com/helm/helm/issues/7326)
# we should use this only for templating (running `helm template ..`)
# usage `helm template ./nvmesh-management --set overrideKubeVersion=1.15`
overrideKubeVersion: false
