#!/usr/bin/env python2

##############################################################################
#  Copyright (C) 2015-2020 Excelero, Inc. All Rights Reserved.               #
#                                                                            #
#  This file is part of Excelero NVMesh software.                            #
#                                                                            #
#  Unauthorized copying of this file, via any medium is strictly prohibited  #
#  Proprietary and confidential                                              #
##############################################################################


import argparse
import subprocess
from tempfile import TemporaryFile
import logging
import platform
import datetime
import re
import os

REGEX_HCAID = r"(mlx\d_\d*)"
REGEX_INSTALLED_MEMORY = r"Mem:\s*(\d*.\d*[A-Za-z]*)"
REGEX_HCA_MAX = r"LnkCap:\s\S*\s\S*\s\S*\s([A-Za-z0-9]*/s),\s\S*\s(\S[0-9]*)"
REGEX_HCA_ACTUAL = r"LnkSta:\s\S*\S*\s([A-Za-z0-9]*/s),\s\S*\s(\S[0-9]*)"
REGEX_HCA_LIST = "(mlx\d_\\d*)\\s*node_guid:\\s*([A-Za-z0-9]*):([A-Za-z0-9]*):([A-Za-z0-9]*):([A-Za-z0-9]*)"
ROCEV2_TARGET_PORT = ("udp", 4791)
MONGODB_PORT = ("tcp", 27017)
RHEL_INBOX_DRIVERS = ['opensm-devel', 'ibutils-devel', 'infiniband-diags', 'librdmacm-utils', 'libibverbs-utils', 'libibumad']
SLES_INBOX_DRIVERS = ["rdma-core", "librdmacm1", "libibmad5", "libibumad3"]
EXCELERO_MLXCONFIG_DB = "/etc/nvmesh/Excelero_mlxconfig.db"
EXCELERO_MANAGEMENT_CONF = "/etc/nvmesh/management.js.conf"
EXCELERO_CONF = "/etc/nvmesh/nvmesh.conf"
DEFAULT_STATISTICS_PORT_COUNT = 5
DEFAULT_NVMESH_MANAGEMENT_PORT = 4001
CMD_GET_ARP="sysctl -n "
CMD_SET_ARP="sysctl -w %s=%s"
CMD_GET_CONF_VALUE = "cat %s | grep %s"
CMD_GET_IP_OF_HOST = "getent hosts %s | awk '{ print $1 }'"
CMD_GET_TUNED_POLICY = "tuned-adm active"
CMD_SET_TUNED_PARAMETERS = "tuned-adm profile latency-performance"
CMD_SET_ONE_QP = "mlxconfig -d %s -b %s set ONE_QP_PER_RECOVERY=1"
CMD_GET_ONE_QP = "mlxconfig -d %s -b %s -e query ONE_QP_PER_RECOVERY | grep ONE_QP_PER_RECOVERY"
CMD_DISABLE_FIREWALL = ["systemctl stop firewalld", "systemctl disable firewalld"]
CMD_SET_FIREWALL_FOR_NVMESH_MGMT_PORT = "firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -p tcp --dport %s -j ACCEPT -m comment --comment Excelero-Management"
CMD_SET_FIREWALL_FOR_ROCEV2 = "firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -p udp --dport " \
                              "4791 -j ACCEPT -m comment --comment RoCEv2-Target"
CMD_SET_FIREWALL_FOR_MOGODB = "firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -p tcp --dport 27017 " \
                              "-j ACCEPT -m comment --comment MongoDB"
CMD_RELOAD_FIREWALL_RULES = "firewall-cmd --reload"
CMD_GET_IRQ_BALANCER_STATUS = "systemctl status irqbalance"
CMD_START_IRQ_BALANCER = "systemctl start irqbalance"
CMD_ENABALE_IRQ_BALANCER = "systemctl enable irqbalance"
CMD_GET_FIREWALLD_STATUS = "systemctl status firewalld | grep Active"
CMD_GET_FIREWALL_CONFIG = "iptables -nL"
CMD_STOP_SUSE_FIREWALL = "systemctl stop SuSEfirewall2"
CMD_DISABLE_SUSE_FIREWALL = "systemctl disable SuSEfirewall2"
CMD_CHECK_FOR_DMIDECODE = "which dmidecode"
CMD_GET_SYSTEM_INFORMATION = "dmidecode | grep -A 4 'System Information'"
CMD_GET_BASE_BOARD_INFORMATION = "dmidecode | grep -A 5 'Base Board Information'"
CMD_CHECK_FOR_SESTATUS = "which sestatus"
CMD_CHECK_FOR_GETENFORCE = "which getenforce"
CMD_SELINUX_GETENFORCE = "getenforce"
CMD_GET_SETSTATUS = "sestatus"
CMD_DISABLE_SELINUX = "sed -i 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config"
CMD_GET_APPARMOR_STATUS = "systemctl status apparmor"
CMD_DISABLE_APPARMOR = "systemctl disable apparmor"
CMD_STOP_APPARMOR = "systemctl stop apparmor"
CMD_GET_APPARMOR_DETAILS = "apparmor_status"
CMD_CHECK_FOR_TUNED_ADM = "which tuned-adm"
CMD_INSTALL_TUNED_SLES = "zypper install -y tuned"
CMD_CHECK_FOR_NVME_CLI = "which nvme"
CMD_GET_NVME_SSD = "nvme list"
CMD_GET_NVME_SDD_NUMA = "lspci -vv | grep -A 10 Volatile | grep -e Volatile -e NUMA"
CMD_INSTALL_NVME_CLI_SLES = "zypper install -y nvme-cli"
CMD_INSTALL_NVME_CLI_RHEL = "yum install -y nvme-cli"
CMD_GET_RNIC_INFO = "for i in $(lspci | awk '/Mellanox/ {print $1}'); do echo $i; echo 'FW level:' | tr '\n' ' '; cat /sys/bus/pci/devices/0000:$i/infiniband/mlx*_*/fw_ver; sudo lspci -s $i -vvv | egrep -e Connect-X -e 'Product Name:' -e Subsystem -e NUMA -e LnkSta: -e LnkCap -e MaxPayload; done"
CMD_GET_OFED_INFO = "ofed_info -n"
CMD_CHECK_RPM = "rpm -q %s"
CMD_GET_IBV_DEVINFO = "ibv_devinfo | grep -e hca_id -e guid"
CMD_GET_IBDEV2NETDEV = "ibdev2netdev -v"
CMD_GET_IBHOSTS = "ibhosts"
CMD_GET_IBSWITCHES = "ibswitches"
CMD_GET_IP_INFO = "ip -s link"
CMD_GET_NVMESH_SERVICES = "service --status-all | grep nvmesh"
CMD_GET_NVMESH_SERVICE_DETAILS = "service %s status"
CMD_STOP_NVMESH_SERVICES = "service %s stop"
CMD_CHECK_IF_SERVICE_IS_RUNNING = "systemctl status %s"
CMD_START_TUNED = "systemctl start tuned"
CMD_ENABLE_TUNED = "systemctl enable tuned"
CMD_INSTALL_SLES_PACKAGE = "zypper install -y %s"
CMD_INSTALL_RHEL_PACKAGE = "yum install -y %s"
CMD_GET_TOMA_LEADER = "cat /var/log/nvmesh/toma_leader_name"
CMD_INSTALL_TUNED_RHEL = "yum install -y tuned"
CMD_INSTALL_PCI_UTILS_SLES = "zypper install -y pciutils"
CMD_INSTALL_PCI_UTILS_RHEL = "yum install -y pciutils"
parser = argparse.ArgumentParser()
parser.add_argument(
    '-v', '--verbose', type=bool, nargs='?', const=True, default=False,
                    help="Activate verbose output mode."
)
parser.add_argument(
    '-s', '--set-parameters', type=bool, nargs='?', const=True, default=False,
                    help="Set the recommended parameters where possible."
)
parser.add_argument(
    '-l', '--run-log-collection', type=bool, nargs='?', const=True, default=False,
                    help="Run the NVMesh log collector together with the NVMesh diag tool."
)
parser.add_argument(
    '-i', '--software-inventory', type=bool, nargs='?', const=True, default=False,
    help="include a list of all installed software packages on this server. RPMs for RH/CentOS and SuSE, "
         "and DEBs for Ubuntu."
)
args = parser.parse_args()
verbose_mode = getattr(args, "verbose")
set_parameters = getattr(args, "set_parameters")
host_name = platform.node()
output = open(host_name + '_' + str(datetime.datetime.utcnow()).replace(" ", "_") + '_nvmesh_diag_output.txt', 'w')

logging.basicConfig(filename='nvmesh_diag.log', format='%(asctime)s\t%(levelname)s\t%(message)s',
                    datefmt='%m/%d/%Y %I:%M:%S %p', level=logging.DEBUG)
logging.debug(
    "Execution Started -------------------------------------------------------------------------------------")
logging.debug("Verbose output enabled: " + unicode(verbose_mode))
logging.debug("Setting recommended parameters: " + unicode(set_parameters))
logging.debug("Storing output to: " + output.name)


def is_management_node():
    return os.path.isfile(EXCELERO_MANAGEMENT_CONF)


def is_client_node():
    return os.path.isfile(EXCELERO_CONF)


def get_cmd_output(cmd_to_execute):
    with TemporaryFile() as t:
        try:
            logging.debug("Running Shell Command: " + cmd_to_execute)
            out = subprocess.check_output(cmd_to_execute, stderr=t, shell=True)
            logging.debug("Success")
            return 0, out
        except subprocess.CalledProcessError as e:
            t.seek(0)
            logging.error(t.read().strip("\n"))
            return e.returncode, cmd_to_execute, t.read()


def get_command_return_code(cmd):
    cmd_output = get_cmd_output(cmd)
    if cmd_output[0] == 0:
        return cmd_output[1]
    elif cmd_output[0] == 3:
        return 3, "Service not running."
    elif cmd_output[0] == 127:
        return print_yellow(cmd.strip().split(" ")[0] + " not found or not installed!")
    elif cmd_output[0] == 255:
        return print_yellow(cmd.strip().split(" ")[
                                0] + " shows no data as there is no IB transport layer. Looks like Ethernet "
                                     "connectivity.")
    elif cmd_output[0] != 0:
        return print_red("Error has occurred while executing " + cmd.strip().split(" ")[
            0] + "! Details can be found in the nvmesh_diag.log file.")


def run_cmd(cmd):
    cmd_output = get_cmd_output(cmd)
    if cmd_output[0] == 0:
        return print_green("Done. Successful.")
    elif cmd_output[0] == 127:
        return print_red("Error! " + cmd.strip().split(" ")[0] + " not found or not installed!")
    elif cmd_output[0] != 0:
        return print_red("Error has occurred while executing " + cmd.strip().split(" ")[
            0] + "! Details can be found in the nvmesh_diag.log file.")


def check_if_service_is_running(service):
    cmd_output = get_cmd_output(CMD_CHECK_IF_SERVICE_IS_RUNNING % service)
    if cmd_output[0] == 0:
        logging.debug("%s is running" % service)
        return True
    elif cmd_output[0] == 3:
        logging.debug("%s is not running" % service)
        return False
    else:
        return None


def print_and_log_info(text):
    logging.info(strip_tabs((text.lstrip("\n")).rstrip(":")))
    print('\033[1m' + '\033[4m' + text + '\033[0m')
    output.write(text + "\n")


def strip_tabs(text):
    text = text.replace("\t", "")
    return text


def print_green(text):
    logging.info(strip_tabs(text))
    output.write(text + "\n")
    return '\033[92m' + text + '\033[0m'


def print_yellow(text):
    logging.warning(strip_tabs(text))
    output.write(text + "\n")
    return '\033[33m' + text + '\033[0m'


def print_red(text):
    logging.error(text + "\n")
    output.write(text)
    return '\033[31m' + text + '\033[0m'


def get_hostname():
    output.write(host_name + "\n\n")
    print(host_name)


def get_hardware_information():
    try:
        if get_cmd_output(CMD_CHECK_FOR_DMIDECODE)[0] == 0:
            system_information = get_command_return_code(CMD_GET_SYSTEM_INFORMATION).split("\n")
            output.write(str(system_information[1].strip() + "\n" + system_information[2].strip() + "\n\n"))
            print("\n".join([system_information[1].strip(), system_information[2].strip()]))
        else:
            print print_yellow("Couldn't find the dmidecode tools. Skipping this step")
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_os_platform():
    try:
        linux_distributuion = platform.linux_distribution()[0].lower()
        if "suse" in linux_distributuion:
            return "sles"
        elif "red" in linux_distributuion:
            return "rhel"
        elif "centos" in linux_distributuion:
            return "rhel"
        elif "oracle" in linux_distributuion:
            return "rhel"
        elif "ubuntu" in linux_distributuion:
            return "ubuntu"
        else:
            print print_yellow(
                "Untested Linux distribution!"), \
                "\nRHEL/CentOS 7.3, 7.4; Oracle Linux 7.4, 7.5, SLES 12 SP3 and Ubuntu LTS 16.4, 18.4 are tested Linux " \
                "distributions for this version."
    except Exception, e:
        logging.debug(e.message)
        print e.message


os_platform = get_os_platform()


def get_os_information():
    try:
        os_details = platform.linux_distribution()[0:2]
        kernel_version = str(platform.release())
        output.write(os_details[0] + os_details[1] + kernel_version + "\n\n")
        print ' '.join([os_details[0], os_details[1], kernel_version,
                        "\nPlease verify this information with the latest support matrix!"])
    except Exception, e:
        logging.debug(e.message)
        print e


def get_and_verify_selinux():
    try:
        if get_cmd_output(CMD_CHECK_FOR_SESTATUS)[0] == 0:
            selinux_status = get_command_return_code(CMD_GET_SETSTATUS).splitlines()
            if not selinux_status[0].split(":")[1].strip() == "disabled":
                print print_yellow("SELinux active. It's recommended to disable SELinux!")
                if verbose_mode is True:
                    for line in selinux_status:
                        print(line)
                if set_parameters is True:
                    if "y" in raw_input("Do you want to disable SELinux now?[Yes/No]: ").lower():
                        print "Disabling SELinux...\t", (run_cmd(CMD_DISABLE_SELINUX))
                        return
                else:
                    return
                print("\n")
            else:
                print print_green("Disabled - OK")
                return
        else:
            print print_yellow("Couldn't find the SElinux policy tools, will try with 'getenforce' now.")
            if get_cmd_output(CMD_CHECK_FOR_GETENFORCE)[0] == 0:
                if "disabled" in get_command_return_code(CMD_SELINUX_GETENFORCE).lower():
                    print print_green("Disabled - OK")
                    return
                else:
                    if set_parameters is True:
                        if "y" in raw_input("Do you want to disable SELinux now?[Yes/No]: ").lower():
                            print(run_cmd(CMD_DISABLE_SELINUX))
                            return
                        else:
                            return
            else:
                if "suse" in platform.linux_distribution()[0].lower():
                    print print_yellow("Couldn't find any SElinux tools or config and the OS is SuSE, will check the"
                                       "AppArmor settings now!")
                    if check_if_service_is_running("apparmor") is True:
                        apparmor_output = get_command_return_code(CMD_GET_APPARMOR_DETAILS)
                        output.write(apparmor_output + "\n")
                        print(print_yellow("AppArmor active!"))
                        if verbose_mode is True:
                            print apparmor_output
                        if set_parameters is True:
                            if "y" in raw_input("Do you want to disable and stop apparmor now?[Yes/No]: ").lower():
                                print "Stopping AppArmor services...\t", run_cmd(CMD_STOP_APPARMOR)
                                print "Disabling AppArmor services...\t", run_cmd(CMD_DISABLE_APPARMOR)
                                return
                            else:
                                return
                    else:
                        print print_green("AppArmor not running - OK")
                        return
                else:
                    print print_yellow("Couldn't find the SElinux or the AppArmor tools. Skipping this step.")
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_and_verify_firewall_suse():
    try:
        firewall_running = check_if_service_is_running("SuSEfirewall2")

        if firewall_running is True:
            print(print_yellow("Firewall active!"))
            if set_parameters is True:
                if "y" in raw_input("Do you want to disable the firewall now?[Yes/No]: ").lower():
                    print "Stopping SuSEfirewall2...\t", run_cmd(CMD_STOP_SUSE_FIREWALL)
                    print "Disabling SuSEfirewall2...\t", run_cmd(CMD_DISABLE_SUSE_FIREWALL)
                    return
                else:
                    return
        elif firewall_running is False:
            print print_green("Disabled - OK")
            return 3

        else:
            print print_yellow("Couldn't verify firewall settings. Skipping this step.")
            return
        return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_management_node_configuration_params():
    # List of ports ('tcp', port)
    rv = []
    try:
        #config.port = 4000; config.webSocketServerPort = 4001;
        for param in ["config.port", "config.webSocketServerPort"]:
            out = get_cmd_output(CMD_GET_CONF_VALUE % (EXCELERO_MANAGEMENT_CONF, param))
            if out[0]:
                print print_red("\tError: Could not parse %s from %s." % (param, EXCELERO_MANAGEMENT_CONF))
            else:
                port = int(out[1].split("=")[1].split(";")[0].strip())
                rv.append(("tcp", port))
        #config.statisticsPorts = [];
        out = get_cmd_output(CMD_GET_CONF_VALUE % (EXCELERO_MANAGEMENT_CONF, "config.statisticsPorts"))
        if out[0]:
            print print_red("\tError: Could not parse config.statisticsPorts from %s." % EXCELERO_MANAGEMENT_CONF)
        else:
            port_string = out[1].split("=")[1].split(";")[0].strip()
            ports = eval(port_string)
            if not ports:
                #config.statisticsCores = 5;
                out = get_cmd_output(CMD_GET_CONF_VALUE % (EXCELERO_MANAGEMENT_CONF, "config.statisticsCores"))

                if out[0]:
                    print print_red("\tError: Could not parse config.statisticsCores from %s. Assuming 5 default ports." % EXCELERO_MANAGEMENT_CONF)

                    number_of_ports = 5
                else:
                    number_of_ports = int(out[1].split("=")[1].split(";")[0].strip())
                for i in range(1, number_of_ports+1):
                    rv.append(("tcp", wssport+i))
            else:
                for port in ports[1:-1].split(","):
                    rv.append(("tcp", port))
    except Exception, e:
        logging.debug(e.message)
        print e.message
    return rv


def get_client_node_configuration_params():
    # List of ports ('tcp', port)
    rv = []
    add_default = False
    try:
        #MANAGEMENT_SERVERS="hostname:port,";
        out = get_cmd_output(CMD_GET_CONF_VALUE % (EXCELERO_CONF, "MANAGEMENT_SERVERS") + " | grep -v '# MANAGEMENT_SERVERS'")
        if out[0]:
            return rv
        list_of_servers = out[1].split("=")[1].split("\"")[1].split(",")
        for server in list_of_servers:
            # future use verify IP is not filtered from port traffic
            hostname = server.split(":")[0]
            ip_out = get_cmd_output(CMD_GET_IP_OF_HOST % hostname)
            if ip_out[0]:
                return rv
            port = server.split(":")[1]
            rv.append(("tcp", port))
            if int(port) == DEFAULT_NVMESH_MANAGEMENT_PORT:
                # When the default port for management communication is set, we can check the default statistics ports as well
                add_default = True
        # TODO: Replace below with valid ports and addresses from MCS (when running / not running)
        # Default Statistic ports if not a management node (and default management port is used)
        if add_default and not is_management_node():
            for i in range(1, DEFAULT_STATISTICS_PORT_COUNT+1):
                rv.append(("tcp", DEFAULT_NVMESH_MANAGEMENT_PORT+i))
    except Exception, e:
        logging.debug(e.message)
        print e.message
    return rv


def check_iptables_output_with_ports(ports, model):
    all_ok = True
    for port in ports:
        if run_cmd("sudo firewall-cmd --query-port=%s/%s" % (port[1], port[0])):
            print print_green("Excelero Management port %s is configured." % port[1])
        else:
            print print_red(
                "Not OK for NVMesh %s operations. "
                "Excelero Management port %s %s must be set and open!" % (model, port[0], port[1]))
            if set_parameters is True:
                if "y" in raw_input("Do you want to open port %s now?[Yes/No]: " % port[1]).lower():
                    print(run_cmd(CMD_SET_FIREWALL_FOR_PORT % port[1]))
                    print "Reloading the firewall rules to apply changes.\n", run_cmd(CMD_RELOAD_FIREWALL_RULES)
                else:
                    all_ok = False
            else:
                all_ok = False
    if all_ok and ports:
        print print_green("For NVMesh %s operations OK. All Excelero Management ports are configured.\n" % model)
    elif all_ok:
        print print_yellow("Unable to get required ports for NVMesh %s operations. Unable to determine Excelero Management ports configuration.\n" % model)
    else:
        print print_red("Some required Excelero Management Ports are not set and open, please review and fix.\n")
    return all_ok


def get_and_verify_firewall_rhel():
    try:
        firewall_running = check_if_service_is_running("firewalld")

        if firewall_running is True:
            print(print_yellow("Firewall active!"))

            if set_parameters is True:
                if "y" in raw_input("Do you want to stop and disable the firewall now?[Yes/No]: ").lower():
                    for command in CMD_DISABLE_FIREWALL:
                        print(run_cmd(command))
                    return

            if set_parameters is True:
                if "n" in raw_input("Do you want to configure the required firewall rules now?[Yes/No]: ").lower():
                    return

            if is_management_node():
                params = get_management_node_configuration_params()
                all_ok = check_iptables_output_with_ports(params, "Management")

            if is_client_node():
                params = get_client_node_configuration_params()
                all_ok = check_iptables_output_with_ports(params, "Client")

            if run_cmd("sudo firewall-cmd --query-port=%s/%s" % (ROCEV2_TARGET_PORT[1], ROCEV2_TARGET_PORT[0])):
                print print_green(
                    "For NVMesh Target operations OK if the Link Layer is Ethernet. RoCEv2 ports are set.")
            else:
                print print_red(
                    "Not OK for NVMesh Target operations if the Link Layer is Ethernet. "
                    "RoCEv2 udp port 4791 must be set and open!")
                if set_parameters is True:
                    if "y" in raw_input("Do you want to open port 4791 now?[Yes/No]: ").lower():
                        print(run_cmd(CMD_SET_FIREWALL_FOR_ROCEV2))
                        print "Reloading the firewall rules to apply changes.\n", run_cmd(CMD_RELOAD_FIREWALL_RULES)

            if run_cmd("sudo firewall-cmd --query-port=%s/%s" % (MONGODB_PORT[1], MONGODB_PORT[0])): 
                print print_green("For MongoDB HA operations OK. MongoDB ports are set.")
            else:
                print print_red("Not OK for MongoDB HA operations. MongoDB TCP port 27017 must be set and open!")
                if set_parameters is True:
                    if "y" in raw_input("Do you want to open port 4791 now?[Yes/No]: ").lower():
                        print(run_cmd(CMD_SET_FIREWALL_FOR_MOGODB))
                        print "Reloading the firewall rules to apply changes.\n", run_cmd(CMD_RELOAD_FIREWALL_RULES)

        elif firewall_running is False:
            print print_green("Disabled - OK")
            return

        else:
            print print_red("Error: Couldn't verify the firewall settings. Skipping this step.")
            return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_and_verify_firewall_ubuntu():
    try:
        firewall_running = check_if_service_is_running("ufw")

        if firewall_running is True:
            print_yellow("Firewall active!")
            print("Please refer to the user documentation and configure the required TCP and UDP ports as documented.")
            if set_parameters is True:
                if "y" in raw_input("Do you want to disable the firewall now?[Yes/No]: ").lower():
                    print "Stopping the Ubuntu Firewall (ufw) ...\t", run_cmd(CMD_STOP_SUSE_FIREWALL)
                    print "Disabling the Ubuntu Firewall (ufw) ...\t", run_cmd(CMD_DISABLE_SUSE_FIREWALL)
                    return
                else:
                    return
        elif firewall_running is False:
            print print_green("Disabled - OK")
            return 3

        else:
            print print_yellow("Couldn't verify firewall settings. Skipping this step.")
            return
        return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_and_verify_firewall():
    try:
        if os_platform == "sles":
            get_and_verify_firewall_suse()
        elif os_platform == "ubuntu":
            get_and_verify_firewall_ubuntu()
        else:
            get_and_verify_firewall_rhel()
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_and_verify_cpu():
    try:
        if get_cmd_output('which lscpu')[0] == 0:
            cpu_info = get_cmd_output("lscpu")[1].split("\n")
            for line in cpu_info:
                output.write(line + "\n")
            output.write("\n")
            actual_cpu_frequency = None
            max_cpu_frequency = None
            for line in cpu_info:
                if "Socket(s)" in line:
                    print line.split(":")[1].strip() + " Physical CPU"
                if "Model name" in line:
                    print line.split(":")[1].lstrip()
                if "CPU MHz" in line:
                    actual_cpu_frequency = float((line.split(":")[1]).strip())
                    max_frequency_info = re.compile("\d+")
                    for frequency in get_cmd_output("dmidecode -s processor-frequency")[1].split("\n"):
                        match = max_frequency_info.search(frequency)
                        if match:
                            max_cpu_frequency = float(match.group(0))
            if actual_cpu_frequency and max_cpu_frequency is not None:
                if max_cpu_frequency - actual_cpu_frequency >= float(100):
                    print print_yellow(
                        "Actual running CPU frequency is lower than the maximum CPU frequency. This might impact performance! "
                        "Check BIOS settings and verify System Tuning settings as below.\n")
                else:
                    print print_green("CPU frequency settings OK.\n")
        else:
            print print_yellow("Couldn't verify the CPU settings. Skipping this step.")
    except Exception, e:
        logging.debug(e.message)
        print e.message


def system_tuning_suse():
    try:
        if get_cmd_output(CMD_CHECK_FOR_TUNED_ADM)[0] != 0:

            print print_yellow("Tis seems to be a server without Tuned installed and running. It's highly"
                               " recommended to install and configure Tuned for best performance results!")
            if set_parameters is True:
                if "y" in raw_input("Do you want to install and configure tuned now?[Yes/No]: ").lower():
                    print "Installing Tuned ...\t", run_cmd(CMD_INSTALL_TUNED_SLES)
                    print "Enabling the Tuned service...\t", run_cmd(CMD_ENABLE_TUNED)
                    print "Starting the Tuned service...\t", run_cmd(CMD_START_TUNED)
                    print "Setting and enabling the throughput-latency tuned policy...\t", run_cmd(CMD_SET_TUNED_PARAMETERS)
                    return
                else:
                    return

        else:
            tuned_service_running = check_if_service_is_running("tuned")

            if tuned_service_running is False:
                print print_yellow("Tuned service is not running! Its hihgly recommended to run the Tuned service")
                if set_parameters is True:
                    if "y" in raw_input("Do you want to start and enable the Tuned service now?[Yes/No] "):
                        print "Enabling the Tuned service...\t", run_cmd(CMD_ENABLE_TUNED)
                        print "Starting the Tuned service...\t", run_cmd(CMD_START_TUNED)
                    else:
                        return

            tuned_adm_info = get_command_return_code(CMD_GET_TUNED_POLICY)
            output.write(tuned_adm_info + "\n")

            if "latency-performance" in tuned_adm_info:
                print(print_green("Tuned profile settings are OK"))
            else:
                print(print_yellow(
                    "Tuned settings is not as recommended! Please run 'tuned-adm profile latency-performance' to set and "
                    "enable the recommended Tuned profile and verify the Tuned service is running."))
                if set_parameters is True:
                    if "y" in raw_input("Do you want to set the recommended tuned parameters now?[Yes/No]: ").lower():
                        print "Setting and enabling the throughput-latency tuned policy...\t", run_cmd(
                            CMD_SET_TUNED_PARAMETERS)
                        return
                    else:
                        return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def system_tuning_ubuntu():
    try:
        if get_cmd_output(CMD_CHECK_FOR_TUNED_ADM)[0] != 0:

            print print_yellow("Tis seems to be a server without Tuned installed and running. It's highly"
                               " recommended to install and configure Tuned for best performance results!")
            if set_parameters is True:
                if "y" in raw_input("Do you want to install and configure tuned now?[Yes/No]: ").lower():
                    print "Installing Tuned ...\t", run_cmd("apt install tuned -y")
                    print "Enabling the Tuned service...\t", run_cmd(CMD_ENABLE_TUNED)
                    print "Starting the Tuned service...\t", run_cmd(CMD_START_TUNED)
                    print "Setting and enabling the throughput-latency tuned policy...\t", run_cmd(CMD_SET_TUNED_PARAMETERS)
                    return
                else:
                    return

        else:
            tuned_service_running = check_if_service_is_running("tuned")

            if tuned_service_running is False:
                print print_yellow("Tuned service is not running! Its hihgly recommended to run the Tuned service")
                if set_parameters is True:
                    if "y" in raw_input("Do you want to start and enable the Tuned service now?[Yes/No] "):
                        print "Enabling the Tuned service...\t", run_cmd(CMD_ENABLE_TUNED)
                        print "Starting the Tuned service...\t", run_cmd(CMD_START_TUNED)
                    else:
                        return

            tuned_adm_info = get_command_return_code(CMD_GET_TUNED_POLICY)
            output.write(tuned_adm_info + "\n")

            if "latency-performance" in tuned_adm_info:
                print(print_green("Tuned profile settings are OK"))
            else:
                print(print_yellow(
                    "Tuned settings is not as recommended! Please run 'tuned-adm profile latency-performance' to set and "
                    "enable the recommended Tuned profile and verify the Tuned service is running."))
                if set_parameters is True:
                    if "y" in raw_input("Do you want to set the recommended tuned parameters now?[Yes/No]: ").lower():
                        print "Setting and enabling the throughput-latency tuned policy...\t", run_cmd(
                            CMD_SET_TUNED_PARAMETERS)
                        return
                    else:
                        return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def system_tuning_rhel():
    try:
        if get_cmd_output(CMD_CHECK_FOR_TUNED_ADM)[0] != 0:

            print print_yellow("This seems to be a server without Tuned installed and running. It's highly"
                               "recommended to install and configure Tuned for best performance results!")
            if set_parameters is True:
                if "y" in raw_input("Do you want to install and configure tuned now?[Yes/No]: ").lower():
                    print "Installing Tuned ...\t", run_cmd(CMD_INSTALL_TUNED_RHEL)
                    print "Enabling the Tuned service...\t", run_cmd(CMD_ENABLE_TUNED)
                    print "Starting the Tuned service...\t", run_cmd(CMD_START_TUNED)
                    print "Setting and enabling the throughput-latency tuned policy...\t", run_cmd(CMD_SET_TUNED_PARAMETERS)
                    return
                else:
                    return

        tuned_service_running = check_if_service_is_running("tuned")

        if tuned_service_running is False:
            print print_yellow("Tuned service is not running! Its hihgly recommended to run the Tuned service")
            if set_parameters is True:
                if "y" in raw_input("Do you want to start and enable the Tuned service now?[Yes/No] "):
                    print "Enabling the Tuned service...\t", run_cmd(CMD_ENABLE_TUNED)
                    print "Starting the Tuned service...\t", run_cmd(CMD_START_TUNED)
                else:
                    return

        tuned_adm_info = get_command_return_code(CMD_GET_TUNED_POLICY)
        output.write(tuned_adm_info + "\n")

        if "latency-performance" in tuned_adm_info:
            print(print_green("Tuned profile settings are OK"))
        else:
            print(print_yellow(
                "Tuned settings is not as recommended! Please run 'tuned-adm profile latency-performance' to set and "
                "enable the recommended Tuned profile and verify the Tuned service is running."))
            if set_parameters is True:
                if "y" in raw_input("Do you want to set the recommended tuned parameters now?[Yes/No]: ").lower():
                    print "Setting and enabling the throughput-latency tuned policy...\t", run_cmd(CMD_SET_TUNED_PARAMETERS)
                    return
                else:
                    return
        return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_and_verify_system_tuning():
    try:
        if os_platform == "sles":
            system_tuning_suse()
        elif os_platform == "ubuntu":
            system_tuning_ubuntu()
        else:
            system_tuning_rhel()

        print("Checking the IRQ balancer...")
        irq_balance_running = check_if_service_is_running("irqbalance")

        if irq_balance_running is True:
            print print_green("The IRQ balancer is running - OK")

        elif irq_balance_running is False:
            print(print_yellow("The IRQ Balancer is not running. This might severely impact the system performance."))
            if set_parameters is True:
                if "y" in raw_input("Do you want to enable and start the IRQ Balance service now?[Yes/No]: "):
                    print "Enabling the IRQ balance service...\t", run_cmd(CMD_ENABALE_IRQ_BALANCER)
                    print "Starting the IRQ balance service...\t", run_cmd(CMD_START_IRQ_BALANCER)
                else:
                    print("No it is. Going on...")

        return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_memory_information():
    try:
        memory_info = get_command_return_code("free -h")
        output.write(memory_info + "\n")
        installed_memory = re.findall(REGEX_INSTALLED_MEMORY, memory_info)[0]
        print(installed_memory + " installed memory.\n")
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_block_device_information():
    try:
        lsblk_output = get_command_return_code("lsblk")
        output.write(lsblk_output + "\n")
        print(lsblk_output)
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_nvmesh_services():
    try:
        if get_cmd_output(CMD_GET_NVMESH_SERVICES)[0] == 0:
            nvmesh_services = get_command_return_code(CMD_GET_NVMESH_SERVICES).splitlines()
            if len(nvmesh_services) > 0:
                return nvmesh_services
        else:
            return None
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_nvmesh_service_details(nvmesh_service):
    try:
        nvmesh_service_details = subprocess.Popen(CMD_GET_NVMESH_SERVICE_DETAILS % nvmesh_service, shell=True,
                                                  stdout=subprocess.PIPE).stdout.read()
        if len(nvmesh_service_details) > 0:
            return nvmesh_service_details
        else:
            return None
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_nvme_storage_info():
    try:
        nvmesh_services = get_nvmesh_services()
        if nvmesh_services is not None:
            print("Found that NVMesh software components are installed already. Checking the NVMesh services now...")
            toma_leader = get_cmd_output(CMD_GET_TOMA_LEADER)[1]
            print "TOMA leader: ", toma_leader
            for service in nvmesh_services:
                nvmesh_service_details = get_nvmesh_service_details(service.split(" ")[0])
                if "ok" in service.lower():
                    print print_green(service)
                    output.writelines(nvmesh_service_details)
                    output.write(toma_leader)
                    if verbose_mode is True:
                        print nvmesh_service_details
                else:
                    print print_red(service)
                    output.write(str(nvmesh_service_details))
                    if verbose_mode is True:
                        print str(nvmesh_service_details)

        if get_cmd_output(CMD_CHECK_FOR_NVME_CLI)[0] == 0:
            print("\nNVMe SSD device information")
            nvme_list_output = get_command_return_code(CMD_GET_NVME_SSD).splitlines()
            if os_platform == "sles":
                if len(nvme_list_output) > 2:
                    for line in nvme_list_output:
                        output.write(line + "\n")
                    for line in nvme_list_output:
                        print(line)
                else:
                    print print_yellow("No NVMe SSD found on this server! This server can only be configured as "
                                       "a NVMesh client.")
                    return
            else:
                nvme_numa_output = get_command_return_code(CMD_GET_NVME_SDD_NUMA)
                if len(nvme_list_output) > 2:
                    for line in nvme_list_output:
                        print(line)
                    print("\n" + nvme_numa_output)
                    output.write("\n" + nvme_numa_output + "\n")
                    for line in nvme_list_output:
                        output.write(line + "\n")
                else:
                    print print_yellow(
                        "No NVMe SSD found on this server! This server can only be configured as a NVMesh "
                        "Client.")
                    return
        else:
            print print_yellow("The nvme-cli tool seems to be missing!")
            if set_parameters is True:
                if "y" in raw_input("Do you want to install the nvme-cli?[Yes/No]: ").lower():
                    if os_platform == "suse":
                        print "Installing nvme-cli ...\t", run_cmd(CMD_INSTALL_NVME_CLI_SLES)
                    elif os_platform == "ubuntu":
                        print "Installing nvme-cli ...\t", run_cmd("apt-get install nvme-cli -y")
                    else:
                        print "Installing nvme-cli ...\t", run_cmd(CMD_INSTALL_NVME_CLI_RHEL)
                    return get_nvme_storage_info()
                else:
                    return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_and_verfy_rnic_conf():
    try:
        if get_cmd_output("which lspci")[0] == 0:
            rnics_output = get_command_return_code(CMD_GET_RNIC_INFO)
            output.write("\n" + rnics_output + "\n")
            rnics = rnics_output.split("\n\n")
            for rnic in rnics:
                max_rnic_speed_and_pcie_width = re.findall(REGEX_HCA_MAX, rnic)
                actual_rnic_speed_and_pcie_with = re.findall(REGEX_HCA_ACTUAL, rnic)
                rnic_details = rnic.splitlines()
                if len(rnic_details) > 0:
                    print("Checking HCA at PCIe address: " + rnic_details[0])
                    print("\tVendor/OEM information:" + rnic_details[2].split("Device")[0])
                    try:
                        if "Product Name" in rnic_details[8]:
                            print "\tHCA Type: " + rnic_details[8].split(":")[1]
                    except:
                        pass
                    print("\tFirmware level: " + rnic_details[1].split(":")[1].strip())

                    if max_rnic_speed_and_pcie_width[0][0] == actual_rnic_speed_and_pcie_with[0][0]:
                        print print_green(
                            "\tHCA PCIe speed settings OK. Running at " + actual_rnic_speed_and_pcie_with[0][0])
                    else:
                        print print_yellow("\tThe HCA is capable of ") + max_rnic_speed_and_pcie_width[0][
                            0] + " but its running at " + actual_rnic_speed_and_pcie_with[0][
                                  0] + "! Check BIOS and HW settings to ensure max performance and a stable environment!"
                    if max_rnic_speed_and_pcie_width[0][1] == actual_rnic_speed_and_pcie_with[0][1]:
                        print print_green(
                            "\tHCA PCIe width settings OK. Running at " + actual_rnic_speed_and_pcie_with[0][1]) + "\n"
                    else:
                        print print_yellow("\tThe HCA is capable of ") + max_rnic_speed_and_pcie_width[0][
                            1] + " but its running at " + actual_rnic_speed_and_pcie_with[0][
                                  0] + "! Check BIOS and HW settings to ensure max performance and a stable environment!\n"
        else:
            print print_yellow("Couldn't run 'lspci'. The pciutils package seems missing. Skipping this step.")
            if set_parameters is True:
                if "y" in raw_input("Do you want to install the pciutils package?[Yes/No]: ").lower():
                    if "suse" in (platform.linux_distribution()[0]).lower():
                        print "Installing pciutils ...\t", run_cmd(CMD_INSTALL_PCI_UTILS_SLES)
                    else:
                        print "Installing pciutils ...\t", run_cmd(CMD_INSTALL_PCI_UTILS_RHEL)
                    return get_and_verfy_rnic_conf()
    except Exception, e:
        logging.debug(e.message)
        print e.message


def check_for_inbox_driver_packages(driver_packages):
    try:
        missing_inbox_drivers = []
        for rpm_package in driver_packages:
            if "Error" in get_command_return_code(CMD_CHECK_RPM % rpm_package):
                missing_inbox_drivers.append(rpm_package)
                output.write("missing " + rpm_package + "!")
                print print_red("\t%s missing " % rpm_package + "!")
        if len(missing_inbox_drivers) != 0:
            return missing_inbox_drivers
        else:
            print print_green("Inbox drivers installed - OK ")
            return missing_inbox_drivers
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_ofed_information():
    try:
        ofed_version = get_command_return_code(CMD_GET_OFED_INFO)
        output.write("OFED: " + ofed_version + "\n")
        if "not found or not installed" in ofed_version:
            if "oracle" in platform.linux_distribution()[0].lower():
                print print_red("OFED not installed! You need to install OFED before getting started with NVMesh.")
                return
            print "OFED not installed! Checking for inbox drivers now."
            if os_platform == "sles":
                missing_inbox_drivers = check_for_inbox_driver_packages(SLES_INBOX_DRIVERS)
                if len(missing_inbox_drivers) != 0:
                    print print_red("OFED is not installed and Inbox drivers are missing! \n"
                                    "You must install either OFED or the missing Inbox drivers!\n")
                    if set_parameters is True:
                        if "y" in raw_input("Do you want to install the Mellanox inbox drivers now?[Yes/No]: "):
                            for package in missing_inbox_drivers:
                                print "Installing package %s ...\t" % package, run_cmd(CMD_INSTALL_SLES_PACKAGE % package)
                            return
                        else:
                            print("No it is. Going on...")
                            return
            elif os_platform == "rhel":
                missing_inbox_drivers = check_for_inbox_driver_packages(RHEL_INBOX_DRIVERS)
                if len(missing_inbox_drivers) != 0:
                    print print_red("OFED is not installed and Inbox drivers are missing! \n"
                                    "You must install either OFED or the missing Inbox drivers!\n")
                    if set_parameters is True:
                        if "y" in raw_input("Do you want to install the Mellanox inbox drivers now?[Yes/No]: "):
                            for package in missing_inbox_drivers:
                                print "Installing package %s ...\t" % package, run_cmd(CMD_INSTALL_RHEL_PACKAGE % package)
                        else:
                            print("No it is. Going on...")
                            return
        else:
            print print_green("OFED installed - OK "), "\nVersion: " + ofed_version + "Please verify this information " \
                                                                                      "with the latest support matrix!"
            return
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_and_veryfy_rdma_conf():
    try:
        if get_cmd_output(CMD_GET_OFED_INFO)[0] == 0:
            ibv_devinfo_output = get_command_return_code(CMD_GET_IBV_DEVINFO)
            output.write(ibv_devinfo_output + "\n")
            hca_list = re.findall(REGEX_HCA_LIST, ibv_devinfo_output, re.MULTILINE)
            for (hca, guid1, guid2, guid3, guid4) in hca_list:
                if guid1 == "0000":
                    print print_red(hca + " guid information seems incorrect or missing. Please check!")
                else:
                    print print_green(hca + " guid OK.")
                if int(re.findall("mlx(\d)", hca)[0]) < 5:
                    continue
                else:
                    if os.path.exists(EXCELERO_MLXCONFIG_DB):
                        one_qp_per_recovery = re.sub("\s\s+", " ", (get_command_return_code(CMD_GET_ONE_QP % (hca, EXCELERO_MLXCONFIG_DB)).lstrip(" ")))
                        if "-E-" in one_qp_per_recovery:
                            print print_red(hca + " will not support RDDA due to firmware limitations on the HCA. If you intent to use RDDA, you "
                                                  "have to update the firmware and enable ONE_QP_PER_RECOVERY on the HCA.")
                        # split_output = [*, ONE_QP_PER_RECOVERY, Default, Current, Next Boot]
                        split_output = one_qp_per_recovery.split(" ")
                        if len(split_output) < 4:
                            print print_red("Unable to determine ONE_QP_PER_RECOVERY value for " + hca + ".")
                            continue
                        for i, item in enumerate(split_output):
                            if "ONE_QP_PER_RECOVERY" in item:
                                index = i
                                break
                        if "True" in split_output[index + 2]:
                            # Current
                            print print_green(hca + " ready and configured for RDDA.")
                        elif "True" in split_output[index + 3]:
                            # Next Boot
                            print print_yellow(hca + " is configured to support RDDA, but requires a reboot before it is valid.")
                        elif "False" in split_output[index + 3]:
                            # Next Boot
                            print print_yellow(hca + " will support RDDA, but is not configured correctly. You have to enable ONE_QP_PER_RECOVERY in "
                                                     "the Mellanox firmware if you want to use RDDA, and then reboot the node.")
                        else:
                            print print_red("Unable to determine ONE_QP_PER_RECOVERY value for " + hca + ".")
                    else:
                        print print_yellow("Cannot find or open the file %s, skipping the RDDA readiness check."
                                     % EXCELERO_MLXCONFIG_DB)
            if verbose_mode is True:
                print(get_command_return_code(CMD_GET_IBDEV2NETDEV))
        else:
            print print_yellow("OFED is not installed! Skipping the R-NIC settings check.")
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_ib_info():
    try:
        if get_cmd_output(CMD_GET_OFED_INFO)[0] != 0:
            print print_yellow("OFED is not installed! Skipping the IB environment check.")
            return
        else:
            ib_hosts = get_command_return_code(CMD_GET_IBHOSTS)
            ib_switches = get_command_return_code(CMD_GET_IBSWITCHES)
            out = ib_hosts + "\n" + ib_switches
            output.write(out + "\n")
            print out
        print("Done.")
        return 0
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_ip_info():
    try:
        out = get_command_return_code("ip -4 a s")
        print out
        output.write(out)
        out = get_command_return_code("ip -s link")
        print "\n", out
        output.write(out)
        print("Done.")
    except Exception, e:
        logging.debug(e.message)
        print e.message


def get_and_verify_arp_values():
    try:
        prefixes = ["net.ipv4.conf.all.", "net.ipv4.conf.default."]
        arp_type_to_value = {"arp_filter":"1", "rp_filter":"2", "arp_ignore":"2", "arp_announce":"2"}
        success = True
        for prefix in prefixes:
            for arp_type, value in arp_type_to_value.iteritems():
                full_type = prefix + arp_type
                out = get_cmd_output(CMD_GET_ARP + full_type)
                if out[0]:
                    print print_red("\tERROR: Cannot get value from sysctl -n %s." % full_type)
                    continue
                arp_value = str(out[1]).strip()
                if value not in arp_value:
                    print print_yellow("\tWARNING: " + full_type + " = " + arp_value + ". Please set to " + value + ", using '" + CMD_SET_ARP % (full_type, value)+ "'.")
                    success = False
        if success:
            print print_green("\n\tARP values correctly assigned.")
        else:
            print print_red("\n\tSome ARP values incorrectly assigned, please review.")
    except Exception, e:
        logging.debug(e.message)
        print e.message


def run_diag():
    print_and_log_info("Collecting Host Name Information:")
    get_hostname()
    print_and_log_info("\nCollecting Hardware Vendor and System Information:")
    get_hardware_information()
    print_and_log_info("\nCollecting Operating System Information:")
    get_os_information()
    print_and_log_info("\nCollecting and Verifying SELinux Information:")
    get_and_verify_selinux()
    print_and_log_info("\nCollecting and Verifying Firewall Information:")
    get_and_verify_firewall()
    print_and_log_info("\nCollecting and Verifying CPU Information:")
    get_and_verify_cpu()
    print_and_log_info("Collecting and Verifying System Tuning Information:")
    get_and_verify_system_tuning()
    print_and_log_info("\nCollecting Memory Information:")
    get_memory_information()
    print_and_log_info("Collecting ARP Information:")
    get_and_verify_arp_values()
    print_and_log_info("\nCollecting High Level Block Device Information:")
    get_block_device_information()
    print_and_log_info("\nCollecting NVMe Storage Device Information:")
    get_nvme_storage_info()
    print_and_log_info("\nCollecting And Verifying Mellanox Driver Information:")
    get_ofed_information()
    print_and_log_info("\nCollecting and Verifying R-NIC information:")
    get_and_verfy_rnic_conf()
    print_and_log_info("\nCollecting And Verifying RDMA Specific Information:")
    get_and_veryfy_rdma_conf()
    print_and_log_info("\nCollecting Infiniband Specific Information:")
    get_ib_info()
    print_and_log_info("\nCollecting IP Interface and Address Information:")
    get_ip_info()
    if args.software_inventory:
        print_and_log_info("\nCollecting Installed Software Packages Information:")
        try:
            if os_platform == "ubuntu":
                output.write(get_command_return_code("dpkg -l"))
            else:
                output.write(get_command_return_code("rpm -qa"))
            print("Saved the software package information in the output file")
        except Exception, e:
            logging.debug(e.message)
            print e.message

    if args.run_log_collection:
        try:
            print_and_log_info("\nRunning the NVMesh Log Collector:")
            print("Please wait ...")
            log_output = get_command_return_code("nvmesh_logs_collector")
            print(log_output)
            output.write(log_output)
        except Exception, e:
            logging.debug(e.message)
            print e.message


if __name__ == "__main__":
    run_diag()
