
{{- $mgmtMongoConn := "" -}}
{{- $statMongoConn := "" -}}
{{- if .Values.mongo.deploy -}}
  {{- $mongoConection := "" -}}
  {{- range $replicaIndex := until (.Values.mongo.replicas|int) -}}
    {{- if gt $replicaIndex 0 -}}
      {{- $mongoConection = printf "%s," $mongoConection -}}
    {{- end -}}
    {{- $mongoConection = printf "%smongo-%d.mongo.%s.svc:27017" $mongoConection $replicaIndex $.Release.Namespace -}}
  {{- end -}}
  {{- $mgmtMongoConn = $mongoConection -}}
  {{- $statMongoConn = $mongoConection -}}
{{- else -}}
    {{- $mgmtMongoConn = .Values.config.mongoConnection.hosts -}}
    {{- $statMongoConn = .Values.config.mongoConnection.hosts -}}
{{- end }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: nvmesh-mgmt-config
  labels:
  {{- include "nvmesh-management.labels" . | nindent 4 }}
data:
  configVersion: {{ .Chart.AppVersion }}
  config: |-
    {
      "loggingLevel": "{{ .Values.config.loggingLevel }}",
      "useSSL": {{ .Values.config.useSSL }},
      "mongoConnection": {
        "hosts": "{{ $mgmtMongoConn }}",
        {{ if gt (.Values.mongo.replicas|int) 1 -}}
        "options": { "replicaSetName": "{{ .Values.mongo.replicaSetName }}" }
        {{- end }}
      },
      "statisticsMongoConnection": {
        "hosts": "{{ $statMongoConn }}",
        {{ if gt (.Values.mongo.replicas|int) 1 -}}
        "options": { "replicaSetName": "{{ .Values.mongo.replicaSetName }}" }
        {{- end }}
      },
      "statisticsCores": {{ .Values.config.statisticsCores }},
      "statisticsIngressPort": {{ .Values.config.statisticsIngressPort }}
    }

