
{{ range $replicaIndex := until (.Values.replicas|int) }}
apiVersion: v1
kind: Service
metadata:
  name: nvmesh-management-svc-{{ $replicaIndex }}
  labels:
    app: nvmesh-management
spec:
  type: ClusterIP
  selector:
    app: nvmesh-management
    statefulset.kubernetes.io/pod-name: nvmesh-management-{{ $replicaIndex }}
  ports:
  - name: ws
    protocol: TCP
    port: {{ $.Values.service.wsPort }}
    targetPort: ws
  {{ range $portIndex := until ($.Values.config.statisticsCores|int) }}
    {{- $port := add 4002 $portIndex -}}
  - name: stats-{{ $portIndex }}
    protocol: TCP
    port: {{ $port }}
    targetPort: {{ $port }}
    {{- if eq $.Values.service.type "NodePort" }}
    nodePort: {{ $.Values.service.nodePort }}
    {{ end }}
  {{ end }}
  {{- if $.Values.service.externalIP }}
  externalIPs: [{{ $.Values.service.externalIP }}]
  {{- end }}
---
{{ end }}

apiVersion: v1
kind: Service
metadata:
  name: nvmesh-management-gui
  labels:
  {{- include "nvmesh-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.guiService.type }}
  selector:
    app: nvmesh-management
  ports:
  - name: "gui"
    protocol: TCP
    port: {{ .Values.guiService.port }}
    targetPort: gui
    {{- if eq .Values.guiService.type "NodePort" }}
    nodePort: {{ .Values.guiService.nodePort }}
    {{ end }}
  {{ if .Values.guiService.externalIP }}
  externalIPs: [{{ .Values.guiService.externalIP }}]
  {{ end }}
  # make sure that connections from a particular client are passed to the same Pod each time
  # without this setting nvmesh-management will reject the login accessToken
  sessionAffinity: {{ .Values.guiService.sessionAffinity }}

