# Source: nvmesh-management/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: nvmesh-management-svc-0
  labels:
    app: nvmesh-management
spec:
  type: ClusterIP
  selector:
    app: nvmesh-management
    statefulset.kubernetes.io/pod-name: nvmesh-management-0
  ports:
  - name: ws
    protocol: TCP
    port: 4001
    targetPort: ws
  - name: stats-0
    protocol: TCP
    port: 4002
    targetPort: 4002
  - name: stats-1
    protocol: TCP
    port: 4003
    targetPort: 4003
  - name: stats-2
    protocol: TCP
    port: 4004
    targetPort: 4004
  - name: stats-3
    protocol: TCP
    port: 4005
    targetPort: 4005
  - name: stats-4
    protocol: TCP
    port: 4006
    targetPort: 4006
---
# Source: nvmesh-management/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: nvmesh-management-gui
  labels:
    
    app.kubernetes.io/version: "2.0.2"
spec:
  type: ClusterIP
  selector:
    app: nvmesh-management
  ports:
  - name: "gui"
    protocol: TCP
    port: 4000
    targetPort: gui
  
  # make sure that connections from a particular client are passed to the same Pod each time
  # without this setting nvmesh-management will reject the login accessToken
  sessionAffinity: ClientIP
---
